### ISSUE TITLE
Can it handle 3 to 4 minutes of long audio?

### ISSUE THREAD

**Issue by speech26ai** [xiaoxue1117/speech-mamba-public#1]
Can it handle 3 to 4 minutes of long audio?

**Comment by xiaoxue1117** [comment]
Thank you for your interest! I have tested audio up to 90 seconds in length, and it can be processed successfully.

**Comment by speech26ai** [comment]
> Thank you for your interest! I have tested audio up to 90 seconds in length, and it can be processed successfully.
Thanks for your reply, I am very interested in this paper of yours, can you release the code at the earliest?

**Comment by xiaoxue1117** [comment]
Certainly, I'll work on releasing it as soon as possible.

**Comment by speech26ai** [comment]
> Certainly, I'll work on releasing it as soon as possible.
Thank you ! 
Do you know any other models that deal with long audio? I'd like to use it for comparison

**Comment by xiaoxue1117** [comment]
> > Certainly, I'll work on releasing it as soon as possible.
> > Thank you !
> > Do you know any other models that deal with long audio? I'd like to use it for comparison

You may use Gemini.

**Comment by speech26ai** [comment]
> Thank you for your interest! I have tested audio up to 90 seconds in length, and it can be processed successfully.
Do you think your model handles 240s of long audio well? thank you !
